INSERT INTO SQLMAP(KEY_, SQL_)
VALUES ('userAdd', 'INSERT INTO USERS (ID, NAME, PASSWORD,LEVEL,LOGIN, RECOMMEND,EMAIL) VALUES(?,?,?,?,?,?,?);');
INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('userGetAll', 'SELECT * FROM USERS ORDER BY ID;');
INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('userGet', 'SELECT * FROM USERS WHERE ID = ?;');
INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('userDelete', 'DELETE FROM USERS;');
INSERT INTO SQLMAP(KEY_, SQL_) VALUES ('userCount', 'SELECT COUNT(*) FROM USERS;');






